### ISSUE TITLE
1.7 - Knife Duplication

### ISSUE THREAD

**Issue by Shadows-of-Fire** [einsteinsci/betterbeginnings#117] opened 2016-01-13 22:56 UTC
When crafting leather strips using a knife in a BB adv crafting table (full structure), the knife is thrown on the ground during crafting, but does not get removed from the crafting grid, thus resulting in infinite knives if strips are left clicked out of the interface.

**Comment by einsteinsci** [comment] 2016-01-13 22:58
Is this only clientside, or do the knives stay duplicated when saving the level? If it's clientside doing certain actions would "revert" the dupe knives into nonexistence.

**Comment by Shadows-of-Fire** [comment] 2016-01-13 23:23
The knives are fully real and usable for crafting.

**Comment by knoxx093** [comment] 2016-01-13 23:25
The title and tags don't match. Is this a 1.8 bug, 1.7 bug, or both?

**Comment by Shadows-of-Fire** [comment] 2016-01-13 23:29
I'm getting it on 1.7, I didnt make the tags.

**Comment by einsteinsci** [comment] 2016-01-15 02:49
@Shadows-of-Fire Sorry that was my mistake. I don't recommend checking issues at 1 AM.

**Comment by einsteinsci** [comment] 2016-05-20 02:35
Confirmed in 1.7.10 version. Does not occur in 1.8.

**Comment by einsteinsci** [comment] 2016-05-20 03:00
Fixed in [](https://github.com/einsteinsci/betterbeginnings-MC1.7/commit/20dc3760fed435bc48b541f470133486b3974603)

**Closed by einsteinsci** 2016-05-20 03:00 UTC
Labels: 1.7, major bug
