### ISSUE TITLE
1.8-0.9.4 tries to access client side classes on a dedicated server

### ISSUE THREAD

**Issue by kreezxil** [einsteinsci/betterbeginnings#81] opened 2015-08-26 23:28 UTC
Looks like better start is pulling a clientside resource on the server- From the server console--

```
[16:51:22] [Server thread/ERROR] [FML]: 16: ASM: com.forgeessentials.playerlogger.PlayerLogger@677085a8 breakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[16:51:22] [Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at net.einsteinsci.betterbeginnings.event.BlockBreakHelper.handleBlockBreaking(BlockBreakHelper.java:133) ~[BlockBreakHelper.class:?]
        at net.einsteinsci.betterbeginnings.event.BBEventHandler.onBlockBreak(BBEventHandler.java:154) ~[BBEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_55_BBEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:530) ~[ForgeHooks.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:280) ~[qx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180785_a(ItemInWorldManager.java:241) ~[qx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:537) ~[rj.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) ~[ml.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) ~[ml.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
        ... 5 more
```

**Comment by kreezxil** [comment] 2015-08-27 00:29
Actually, this also causes a permanent server crash

Issue: crashes dedicated server hard while playing while looking for client side classes using version 1.8-0.9.4 with forge b1504

crash report:
https://gist.github.com/75e7cc1ba6feec5b1b18

fml server latest:
https://gist.github.com/3808c30c562240765c4b

**Comment by einsteinsci** [comment] 2015-08-27 03:25
Duplicate of #76. The bugfix will be present in the next update, as soon as I get NEI and CCC to stop crashing my dev workspace.

**Closed by einsteinsci** 2015-08-27 03:25 UTC
Labels: duplicate
