### ISSUE TITLE
Advanced Crafting leaves some catalysts sometimes

### ISSUE THREAD

**Issue by knoxx093** [einsteinsci/betterbeginnings#100] opened 2015-12-30 16:54 UTC
Version: 0.9.5 R5a

I looked in commits, didn't see anything that seemed to be related.

Steps:
Place 3 stone and then 2 sticks as if to craft the BB stone pickaxe.
Place 2 leatherStrip into the top catalyst slot as indicated.
Click result slot to obtain stone pickaxe.
Only 1 leatherStrip is consumed. 1 leatherStrip remains in table

**Comment by einsteinsci** [comment] 2015-12-30 17:07
That's weird. I remember fixing a [similar bug](https://github.com/einsteinsci/betterbeginnings/issues/91), and when testing I don't remember anything like this happening. I'll check this out when I get home.

**Comment by einsteinsci** [comment] 2015-12-30 17:11
Are there any other tools that are affected by this? Does this occur when the config option "Allow String as Tool Binding" is set to `false`?

**Comment by knoxx093** [comment] 2015-12-30 17:16
I've only tested with the default config options. 
Stone axe appears to leave a strip behind but its a "phantom" item that goes away if you try to pick it up.
Stone shovel only needs 1 strip and works as intended.

**Comment by knoxx093** [comment] 2015-12-30 18:53
Its might have something to do with only having 1 stone in each of the top slots, if i use stacks of any size it appears to work as intended.

**Comment by einsteinsci** [comment] 2015-12-31 00:09
Yeah, the catalyst math has always been kind of funky. The algorithm is pretty old and assumes that you have each catalyst in only one slot. To solve this I'll need to do some sort of filling tracker that treats the catalysts as a requirement that needs to be filled. Only when it finds all are filled does it work.

FYI, don't ever use `System.out.println()` in a MC mod. Use `FMLLog.log()` instead. My mod has its own `LogUtil` class you can use; it encapsulates better.

**Comment by knoxx093** [comment] 2015-12-31 00:22
Good to know. I've not been ModdingMC very long. I do really like this project though. I will poke at it more when I get a chance!

**Comment by knoxx093** [comment] 2015-12-31 05:28
Having done some testing, the problem appears to be this: 
```
AdvancedRecipe advRecipe = container.getLastAdvancedRecipe();
```

This line is returning the recipe for the Stone Hoe instead of the Stone Pickaxe

**Comment by einsteinsci** [comment] 2015-12-31 17:19
This looks like it was caused by a previous bugfix, in fact, the same one I mentioned earlier. I might have to redo the entire algorithm.

**Comment by knoxx093** [comment] 2015-12-31 17:24
Some testing with moving 
```
AdvancedRecipe advRecipe = container.getLastAdvancedRecipe();
```
up to line ~130 after 
```
onCrafting(resultStack);
```
seems to fix it.

**Comment by einsteinsci** [comment] 2015-12-31 17:31
I did some testing, and it looks like this problem only occurs if you put in the stone one at a time (click click click), rather than right-click dragging the stone across the top (which is what I always do when crafting). That explains why I never caught this.

Moving it up to L130 doesn't entirely fix it. If you close and reopen the GUI, and then follow the steps of putting in the sticks and then the stone, then exactly two leather strips, you'll still have the ghost item stuck in the clientside catalyst slot.

**Comment by knoxx093** [comment] 2015-12-31 17:36
You'll have the ghost item but at least its only a ghost. The problem before was an actual item remaining that you could take out.
I have the same problem when right click dragging across the top as well.
I believe the issue stems from having a single stone in the top left slot, when that stone is removed and you hit the race condition, the findRecipeMatch returns the stone hoe recipe before we've started taking out catalyst mats.

**Comment by einsteinsci** [comment] 2015-12-31 17:38
Just tried putting the whole thing in an `if (player.worldObj.isRemote)`. Did not work, only made everything ghost-y.

**Closed** 2015-12-31 19:04 UTC
Labels: 1.8, major bug, unconfirmed
