### ISSUE TITLE
Server crash when kiln is accessed while holding a torch.

### ISSUE THREAD

**Issue by RebirthGaming** [einsteinsci/betterbeginnings#120] opened 2016-02-12 21:46 UTC
When players on a server try right clicking the kiln while holding a torch, the server crashes.  

Quite possibly a mod compatibility issue, such as dynamic lighting, but not sure.

http://pastebin.com/FB79E3wa

**Comment by zHawky** [comment] 2016-02-17 12:41
I have same issue, something weird with torch from enviromine.

**Comment by RebirthGaming** [comment] 2016-02-17 14:32
Didn't even think of that. May have to somehow disable EnviroMine's torches in the mean time. 

@Funwayguy, can you look into this?

**Comment by Leviathan143** [comment] 2016-12-23 20:34
Sorry for not getting around to looking at this, I mistook it as a dupe of #127. 127 was unreproducible , and hence we couldn't fix it. 127 may be related to this error, as the same error shows up later in this issue.

Anyway, I've started debugging and I'm getting somewhere. I have the beginnings of an idea of what's wrong.

**Comment by Leviathan143** [comment] 2016-12-23 20:53
Okay, found the issue, it's due to a typo in Enviromine
https://github.com/EnviroMine/EnviroMine-1.7/blob/master/src/main/java/enviromine/handlers/EM_EventManager.java#L455
Enviromine is passing the y coordinate as both the y coord and the z coord, since there is no kiln there, BB crashes.

**Closed** 2017-10-28 21:54 UTC
Labels: 1.7, compatibility, dedicated server, unconfirmed
